// <auto-generated />
namespace HospitalProject_W2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedepartmentinstaff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedepartmentinstaff));
        
        string IMigrationMetadata.Id
        {
            get { return "202204031947182_changedepartmentinstaff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
